import 'dart:io';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  static Future<void> exportReport(File imageFile, String reportText, int? severityScore, {Uint8List? segmentationMask}) async {
    final pdf = pw.Document();
    
    final imageImage = pw.MemoryImage(await imageFile.readAsBytes());
    
    String cleanReport = reportText.replaceAll(RegExp(r'(?:Severity Score|Severity):\s*\**\s*\d+\s*(?:\/10)?\**\n?'), '').trim();
    
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text("WoundWise Analysis Report", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.center,
                children: [
                   pw.Image(imageImage, height: segmentationMask != null ? 150 : 250),
                   if (segmentationMask != null) ...[
                     pw.SizedBox(width: 20),
                     pw.Image(pw.MemoryImage(segmentationMask), height: 150),
                   ],
                ],
              ),
              pw.SizedBox(height: 20),
              
              if (severityScore != null) ...[
                pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  color: PdfColors.grey200,
                  width: double.infinity,
                  child: pw.Row(
                    children: [
                      pw.Text("Severity Score: ", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
                      pw.Text("$severityScore / 10", style: const pw.TextStyle(fontSize: 16)),
                    ]
                  )
                ),
                pw.SizedBox(height: 20),
              ],
              
              pw.Text("AI Assessment", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Text(cleanReport, style: const pw.TextStyle(fontSize: 12, lineSpacing: 2)),
              
              pw.Spacer(),
              pw.Divider(),
              pw.Center(
                child: pw.Text(
                  "This report is generated by AI and is not a substitute for professional medical advice.", 
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                  textAlign: pw.TextAlign.center
                ),
              ),
            ]
          );
        }
      )
    );
    
    await Printing.sharePdf(bytes: await pdf.save(), filename: 'WoundWise_Report.pdf');
  }
}
